version: "3.8"

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_URL: mongodb://db:27017/patientdb
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - patientdata:/data/db

volumes:
  patientdata: